name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: docker build -t blazorwebapp:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name myblazorapp blazorwebapp:latest
          sleep 120
          docker logs myblazorapp

      - name: Stop and remove Docker container
        run: |
          docker stop myblazorapp
          docker rm myblazorapp
